server:
  port: 8080
  error:
    #    include-stacktrace: never
    include-binding-errors: always
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 30MB
  profiles:
    include:
      - security
      - data
      - mail
      - scheduler
